### ISSUE TITLE
After the page is refreshed, all open tabs except the current page are closed

### ISSUE THREAD

**Issue by LazyEar0** [BlazorComponent/MASA.Blazor.Pro#123]
![刷新后](https://user-images.githubusercontent.com/95004531/150762642-2b779b4c-7016-4111-a97d-fe67dc47d934.png)
![刷新后0](https://user-images.githubusercontent.com/95004531/150762659-328dca40-2004-4596-82c8-5b2a347bd607.png)

**Comment by 15168440402** [comment]
The current design function of multi-tab is like this, and the multi-tab function will not be recorded for the time being.
