### ISSUE TITLE
In the Shop, check the product details of product A, and then open Product A‘s  PageTab of the  details . Go back to the Shop and open the product details of product B, but the Product B ‘s  PageTab of the  details  is not created 

### ISSUE THREAD

**Issue by LazyEar0** [BlazorComponent/MASA.Blazor.Pro#126]
![pagetab0](https://user-images.githubusercontent.com/95004531/152935950-3a75a0e7-2f85-4d86-b785-0d64c642e214.png)
![pagetab](https://user-images.githubusercontent.com/95004531/152935965-ef8e6f98-2904-4bb7-a730-17885bccd283.png)

**Comment by 15168440402** [comment]
At present, it will be done according to multiple detail pages sharing a tab page, and then this function will be used to test
