### ISSUE TITLE
tab页生命周期不对，打开页面会执行1次dispose关闭页面会执行2次dispose

### ISSUE THREAD

**Issue by doddgu** [BlazorComponent/MASA.Blazor.Pro#138]
tab页生命周期不对，打开页面会执行1次dispose关闭页面会执行2次dispose
详细问题演示见下面的仓库：
https://gitee.com/sonic3k/masapro-issues.git
执行后直接控制台查看输出

from: https://gitee.com/blazorcomponent/MASA.Blazor.Pro/issues/I55PEG

**Comment by MayueCif** [comment]
It's not pro problem,fix this problem in masa blazor 0.4.0.
