### ISSUE TITLE
PageTab . The new pagetab is not automatically located

### ISSUE THREAD

**Issue by LazyEar0** [BlazorComponent/MASA.Blazor.Pro#148]
页签过多时，在第一页打开新的页签， 没有自动定位到新的页签；

https://user-images.githubusercontent.com/95004531/178196339-f4f332c2-0de2-4360-b7dd-863979a600f4.mp4

**Comment by capdiem** [comment]
maybe fixed in https://github.com/BlazorComponent/MASA.Blazor.Pro/pull/151 .
