### ISSUE TITLE
PageTab . The pagetab are not fully displayed

### ISSUE THREAD

**Issue by LazyEar0** [BlazorComponent/MASA.Blazor.Pro#149]
页签过多时，选中第一页最后一个页签，没有自动显示全部，切换到第二页才显示全

https://user-images.githubusercontent.com/95004531/178196587-d11cc3f2-2004-4da8-a7ff-2a44490b7f06.mp4

**Comment by capdiem** [comment]
maybe fixed in https://github.com/BlazorComponent/MASA.Blazor.Pro/pupll/151 .
