### ISSUE TITLE
拉最新的源码，PageTabItems的效果与官网demo不一样，切换Tab时不能将user/view/后面的id带上

### ISSUE THREAD

**Issue by kylixfans** [BlazorComponent/MASA.Blazor.Pro#173]
### Description

查看用户详情，打开新Tab【展示】，Url是http://localhost:5000/app/user/view/b48bda53-57bd-4f9b-a680-4fb0d89f55da
![图片](https://user-images.githubusercontent.com/6711407/203697175-2f7cc053-2ba8-40f8-9b7c-40cc767e8763.png)

切换回用户列表页， Url切换为http://localhost:5000/app/user/list
![图片](https://user-images.githubusercontent.com/6711407/203697325-1dafd846-b681-4d8b-a9bb-2c68435aeac8.png)

再切换回展示页，Url却变成：http://localhost:5000/app/user/view，丢失了后面的用户Id
![图片](https://user-images.githubusercontent.com/6711407/203697526-21fda2a9-ce40-4fc4-9bc6-38807b8380d9.png)

### OS version

Win10

### Visual Studio version

VS2022

### Additional context

.Net6

**Comment by doddgu** [comment]
@15168440402 PTAL

**Comment by capdiem** [comment]
@kylixfans 线上引用的Masa Blazor是0.6的正式版。main分支相当于开发分支，目前引用的Masa Blazor是预览版，功能不太稳定。你的问题在重构PageTabs之后已经修复。

**Comment by doddgu** [comment]
那我先关闭了，有问题可以再 reopen
