### ISSUE TITLE
Make the PageTab or Breadcrumb component be marked as "position:fixed;" as MAppBar component

### ISSUE THREAD

**Issue by CuteLeon** [BlazorComponent/MASA.Blazor.Pro#177]
### Issue type

sample request

### Description

Mark the PageTab or Breadcrumb component as a fixed position as the AppBar component, so that the PageTab or Breadcrumb component is always visible when the tab page content scrolls.

### Screenshots

**PageTab item was covered rather than permanently displayed on the top.**
![image](https://user-images.githubusercontent.com/17419770/214664877-48987c0a-ecd0-4a70-b30d-bef4102c8347.png)

### Which OS or Visual Studio versions did you see the issue on?

Windows 11 / Visual Studio 2022

**Comment by doddgu** [comment]
@capdiem It maybe need pagetab support？

**Comment by capdiem** [comment]
Just need to update the example.
