### ISSUE TITLE
MASA.Pro更新MASA.Blazor 1.0.0-preview.4版本后菜单抽屉显示异常

### ISSUE THREAD

**Issue by Caspersure** [BlazorComponent/MASA.Blazor.Pro#180]
### Description

问题概述:
1.当前页面的对应菜单项没有右边框提示
2.收起展开按钮在收起后无法再展开
具体请见下图

### Screenshots

![Snipaste_2023-02-24_09-31-11](https://user-images.githubusercontent.com/62390646/221070325-c6cd51fe-130a-49b1-af84-c442a96b4228.png)

**Comment by doddgu** [comment]
@capdiem PTAL
