### ISSUE TITLE
Management header navigation bar menu, icon is not centered

### ISSUE THREAD

**Issue by LazyEar0** [BlazorComponent/MASA.Blazor.Pro#20]
1.Click the heart in the header navigation bar；
2.Click on the heart to select or cancel the menu；

Heart is not centered
![Heart is not centered](https://user-images.githubusercontent.com/95004531/146718217-068b6ab3-a15d-43de-a044-ebd3bb7f4a2c.png)

**Comment by 15168440402** [comment]
already fixed
