### ISSUE TITLE
Change the title to "MASA Blazor Pro"

### ISSUE THREAD

**Issue by LazyEar0** [BlazorComponent/MASA.Blazor.Pro#3]
![name](https://user-images.githubusercontent.com/95004531/146501040-688ddb4b-ba9f-4f25-85a9-ce492440a090.png)

**Comment by doddgu** [comment]
It's not a problem, because masastack.com is for the record. Now is using cname, it's not a real url. Next week will resolve it.

**Comment by doddgu** [comment]
But, it has another problem, icon isn't masa.
