### ISSUE TITLE
The navigation bar should have only one menu open

### ISSUE THREAD

**Issue by LazyEar0** [BlazorComponent/MASA.Blazor.Pro#5]
![Only one menu should be expanded](https://user-images.githubusercontent.com/95004531/146702814-61c40ec4-6394-4dcd-a065-73481c4ec960.png)

**Comment by 15168440402** [comment]
The function of our navigation bar is to expand multiple first-level menus. When you click on the second-level menu, it will automatically shrink the other first-level menus.
